env:
  es2021: true
  node: true
  browser: true
extends:
  - eslint:recommended
  - plugin:import/recommended
  - airbnb-base
parserOptions:
  ecmaVersion: 11
  sourceType: module
rules:
  no-console: 0
  import/extensions: 0
